todo_list/urls.py
from django.urls import path

from todo_list.views import (
    IndexListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagsListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    toggle_task_status,
)


urlpatterns = [
    path("", IndexListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("<int:pk>/toggle/", toggle_task_status, name="task-toggle"),
    path("tags/", TagsListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "todo_list"

todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class Task(models.Model):
    description = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self):
        return (
            f"{self.description} (completed: {self.is_completed})"
            f"Created at: {self.description}"
            f"Deadline: {self.deadline}"
        )

todo_list/forms.py
from django import forms
from todo_list.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(
            attrs={
                "type": "datetime-local",
            }
        ),
        required=False,
    )

    class Meta:
        model = Task
        fields = [
            "description",
            "deadline",
            "tags",
        ]

todo_list/views.py
from django.http import (
    HttpRequest,
    HttpResponseRedirect,
    HttpResponse
)
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class IndexListView(generic.ListView):
    model = Task
    template_name = "todo_list/index.html"
    context_object_name = "tasks"
    paginate_by = 3


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:index")


class TagsListView(generic.ListView):
    model = Tag
    template_name = "todo_list/tags.html"
    context_object_name = "tags"
    paginate_by = 3


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")


def toggle_task_status(
        request: HttpRequest,
        pk: int
) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.is_completed = not task.is_completed
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo_list:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      {% block title %}<title>TODO list</title>{% endblock %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
            integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
            crossorigin="anonymous">
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>

  <body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                {% block sidebar %}
                    {% include "includes/sidebar.html" %}
                {% endblock %}
            </div>
            <div class="col-sm-10 ">
                {% block content %}
                {% endblock %}

                {% block pagination %}
                    {% include "includes/pagination.html" %}
                {% endblock %}
            </div>
        </div>
    </div>
  </body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo_list:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo_list:tag-list' %}">Tags</a></li>
</ul>

templates/todo_list/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>
    TODO list
    <a class="btn btn-primary link-to-page" href="{% url 'todo_list:task-create' %}">Add task</a>
  </h1>
  {% if tasks %}
    {% for task in tasks %}
      <li class="page-item-list">
        <h4>
          {{ task.description }}
        <strong>
          {% if task.is_completed %}
            <span class="task-done">Done</span>
          {% else %}
            <span class="task-not-done">Not done</span>
          {% endif %}
        </strong>
        {% if task.is_completed %}
          <a class="btn btn-secondary link-to-page" href="{% url 'todo_list:task-toggle' pk=task.id %}">
            Undo
          </a>
        {% else %}
          <a class="btn btn-success link-to-page" href="{% url 'todo_list:task-toggle' pk=task.id  %}">
            Complete
          </a>
        {% endif %}
        </h4>
        <p class="publish-date">
          Created: {{ task.created_at }}
          {% if not task.is_completed and task.deadline %}
            <strong class="deadline">Deadline: {{ task.deadline }}</strong>
          {% endif %}
        </p>
        <p>
          {% if task.tags.all %}
            <span class="tag-list">
            Tags:
            {% for tag in task.tags.all %}
              {{ tag.name }}
            {% endfor %}
            </span>
          {% endif %}
          <strong>
            <a style="text-decoration: none" href="{% url 'todo_list:task-update' pk=task.id  %}">
              Update
            </a>
            <a style="text-decoration: none" href="{% url 'todo_list:task-delete' pk=task.id  %}">
              Delete
            </a>
           </strong>
        </p>
      </li>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url "todo_list:tag-list" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tags.html
{% extends 'base.html' %}
{% block content %}
  <h1>
    Tags
    <a class="btn btn-primary link-to-page" href="{% url 'todo_list:tag-create' %}">Add</a>
  </h1>

  {% if tags %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tags %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo_list:tag-update' tag.id %}" class="btn btn-warning">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'todo_list:tag-delete' tag.id %}" class="btn btn-danger">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url "todo_list:index" %}" class="btn btn-secondary">Cancel</a>
    <input type="submit" value="Confirm" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}